[package]
name = "contract-app"
version = "0.1.0"
edition = "2024"

[dependencies]
sails-rs = "0.8.1"

[dev-dependencies]
sails-rs = { version = "0.8.1", features = ["gstd", "std"] }
tokio = { version = "1.41", features = ["rt", "macros"] }